languageCode: "en-us"
title: "Nick Hester"
theme: "hugo-PaperMod"
params:
  defaultTheme: "auto"
  homeInfoParams:
    Title: "Hi there 👋"
    Content: "I'm Nick Hester. Software Engineer, tinkerer, nerd."
  socialIcons:
    - name: github
      url: "https://github.com/nickhstr"
    - name: linkedin
      url: "https://www.linkedin.com/in/nickhstr/"
  description: "Nick Hester's personal site."
  showShareButtons: true
  showReadingTime: true
  assets:
    favicon: "/icons/favicon.ico"
    favicon16x16: "/icons/favicon-16x16.png"
    favicon32x32: "/icons/favicon-32x32.png"
    apple_touch_icon: "/icons/apple-touch-icon-180x180.png"
    manifest: "/manifest.json"
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 1
    - identifier: "archive"
      name: "Archive"
      url: "/archive/"
      weight: 2
    - identifier: "search"
      name: "Search"
      url: "/search/"
      weight: 3
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 4
enableRobotsTXT: true
enableGitInfo: true
minify:
  minifyOutput: true
